#!/usr/bin/env python3
"""
igc_to_c.py  —  Convert an IGC flight log to STM32 pressure_data.c / .h
Usage:  python igc_to_c.py yourflight.igc

Outputs:
  pressure_data.c   — drop into Core/Src/
  pressure_data.h   — drop into Core/Inc/
  igc_summary.txt   — flight stats + recommended #define values
"""

import sys
import os
import math

def alt_to_hpa(alt_m):
    """Convert pressure altitude (metres) back to hPa via ISA barometric formula."""
    P0 = 1013.25   # hPa at sea level
    T0 = 288.15    # K
    L  = 0.0065    # lapse rate K/m
    R  = 8.31446
    M  = 0.028964
    g  = 9.80665
    exp = (g * M) / (R * L)
    return P0 * math.pow(1.0 - (L * alt_m) / T0, exp)

def parse_igc(path):
    altitudes = []   # metres, from B-records
    times     = []   # seconds since midnight

    with open(path, 'r', errors='replace') as f:
        for line in f:
            line = line.strip()
            if not line.startswith('B'):
                continue
            if len(line) < 35:
                continue
            try:
                hh = int(line[1:3])
                mm = int(line[3:5])
                ss = int(line[5:7])
                t  = hh * 3600 + mm * 60 + ss

                validity = line[24]          # A = 3D fix, V = no fix
                palt = int(line[25:30])      # pressure altitude, metres

                # Skip clearly invalid pressure altitudes
                if palt < -500 or palt > 10000:
                    continue

                times.append(t)
                altitudes.append(palt)
            except (ValueError, IndexError):
                continue

    return times, altitudes

def fill_gaps(times, altitudes):
    """Fill any 1-second gaps in the B-record sequence by linear interpolation."""
    if not times:
        return times, altitudes

    filled_t   = []
    filled_alt = []

    for i in range(len(times)):
        filled_t.append(times[i])
        filled_alt.append(altitudes[i])
        if i < len(times) - 1:
            gap = times[i+1] - times[i]
            if 1 < gap <= 10:   # fill gaps up to 10 seconds
                for j in range(1, gap):
                    frac = j / gap
                    filled_t.append(times[i] + j)
                    filled_alt.append(altitudes[i] + frac * (altitudes[i+1] - altitudes[i]))

    return filled_t, filled_alt

def compute_rates(altitudes):
    """Compute hPa/s rate for each sample (1-second delta)."""
    pressures = [alt_to_hpa(a) for a in altitudes]
    rates = [0.0]
    for i in range(1, len(pressures)):
        rates.append(pressures[i] - pressures[i-1])
    return pressures, rates

def write_output(pressures, rates, flight_duration_s, out_dir):
    n = len(pressures)

    # Stats
    max_climb   = max(-r for r in rates)          # most negative rate
    max_descent = max(rates)                       # most positive rate
    p_min = min(pressures)
    p_max = max(pressures)

    # Recommended climb scale: 90th percentile of absolute rates (ignores spikes)
    abs_rates = sorted(abs(r) for r in rates)
    p90_index = int(0.90 * len(abs_rates))
    climb_scale = round(abs_rates[p90_index] * 1.5, 2)
    climb_scale = max(climb_scale, 0.5)

    # Recommended deadband: just above sensor noise floor
    deadband = round(abs_rates[int(0.05 * len(abs_rates))] + 0.02, 3)
    deadband = max(deadband, 0.02)

    # --- pressure_data.h ---
    h_content = f"""#ifndef PRESSURE_DATA_H
#define PRESSURE_DATA_H

#include 

/* Generated by igc_to_c.py from real IGC flight data.
 * Flight duration : {flight_duration_s} seconds ({flight_duration_s//60} min {flight_duration_s%60} s)
 * Pressure range  : {p_min:.1f} – {p_max:.1f} hPa
 * Max climb rate  : {max_climb:.2f} hPa/s
 * Max descent rate: {max_descent:.2f} hPa/s
 */

#define PRESSURE_SAMPLES {n}u

extern const float pressure_hPa[PRESSURE_SAMPLES];

#endif
"""

    # --- pressure_data.c ---
    # Format as rows of 8 values
    vals = [f"{p:.2f}f" for p in pressures]
    rows = []
    for i in range(0, len(vals), 8):
        chunk = vals[i:i+8]
        rows.append("    " + ", ".join(chunk) + ",")
    # remove trailing comma on very last entry
    last = rows[-1].rstrip(",")
    rows[-1] = last

    array_body = "\n".join(rows)

    c_content = f"""#include "pressure_data.h"

/* Generated by igc_to_c.py from real IGC flight data.
 * One entry per second of flight.
 * Converted from IGC pressure altitude (metres) via ISA barometric formula.
 * Negative delta between consecutive samples = climbing.
 * Positive delta = descending.
 */
const float pressure_hPa[PRESSURE_SAMPLES] = {{
{array_body}
}};
"""

    # --- igc_summary.txt ---
    summary = f"""IGC conversion summary
======================
Samples          : {n}
Duration         : {flight_duration_s} s  ({flight_duration_s//60} min {flight_duration_s%60} s)
Pressure range   : {p_min:.1f} – {p_max:.1f} hPa
Max climb rate   : {max_climb:.2f} hPa/s  (pressure falling)
Max descent rate : {max_descent:.2f} hPa/s  (pressure rising)

Recommended #defines for main.c
--------------------------------
#define VARIO_DEADBAND_HPA   {deadband:.3f}f
#define GREEN_BLINK_MIN_MS   80u
#define GREEN_BLINK_MAX_MS   800u
#define CLIMB_SCALE_HPA      {climb_scale:.2f}f
#define RED_ON_MIN_MS        500u
#define RED_ON_MAX_MS        1500u
#define RED_OFF_MS           200u

Note: CLIMB_SCALE_HPA is set to 1.5x the 90th-percentile rate so
the LEDs respond visibly to most of the flight without saturating.
Increase it if the LED always blinks at maximum speed.
"""

    with open(os.path.join(out_dir, "pressure_data.h"), "w") as f:
        f.write(h_content)
    with open(os.path.join(out_dir, "pressure_data.c"), "w") as f:
        f.write(c_content)
    with open(os.path.join(out_dir, "igc_summary.txt"), "w") as f:
        f.write(summary)

    print(summary)
    print(f"Written: pressure_data.h, pressure_data.c, igc_summary.txt")

def main():
    if len(sys.argv) < 2:
        print("Usage: python igc_to_c.py yourflight.igc")
        sys.exit(1)

    path = sys.argv[1]
    if not os.path.exists(path):
        print(f"File not found: {path}")
        sys.exit(1)

    out_dir = os.path.dirname(os.path.abspath(path))

    print(f"Parsing {path} ...")
    times, altitudes = parse_igc(path)

    if not times:
        print("No valid B-records found. Check that this is a valid IGC file.")
        sys.exit(1)

    print(f"Found {len(times)} B-records.")

    times, altitudes = fill_gaps(times, altitudes)
    print(f"After gap-fill: {len(altitudes)} samples.")

    # Warn if very large
    if len(altitudes) > 7200:
        print(f"Warning: {len(altitudes)} samples is a long flight ({len(altitudes)//3600}h+).")
        print("The array will be large but will fit in STM32L4R5 flash (2 MB).")

    duration = times[-1] - times[0] if len(times) > 1 else len(times)
    pressures, rates = compute_rates(altitudes)
    write_output(pressures, rates, duration, out_dir)

if __name__ == "__main__":
    main()
