#ifndef PRESSURE_DATA_H
#define PRESSURE_DATA_H

#include 

/* Generated by igc_to_c.py from real IGC flight data.
 * Flight duration : 23722 seconds (395 min 22 s)
 * Pressure range  : 638.3 – 915.6 hPa
 * Max climb rate  : 0.76 hPa/s
 * Max descent rate: 0.77 hPa/s
 */

#define PRESSURE_SAMPLES 23723u

extern const float pressure_hPa[PRESSURE_SAMPLES];

#endif
